export const TIER_BRANDS = {
  A: ["Toteme","Acne Studios","Filippa K","Tiger of Sweden","Stine Goya","Ganni","By Malene Birger","Rodebjer","Hope Stockholm","Our Legacy","3.1 Phillip Lim","Alaia","Alexander McQueen","ATP Atelier","APC","Balenciaga","Baserange","Baum und Pferdgarten","Bottega Veneta","Burberry","Carhartt","Carhartt WIP","Celine","Chanel","Chloe","COS","Dagmar","Dior","Dr Martens","Eytys","Flattered","House of Dagmar","Gant","Gucci","Patagonia","Isabel Marant","Jacquemus","Jil Sander","Levi's","Loewe","Louis Vuitton","Ralph Lauren","Maison Margiela","Marni","Miu Miu","Moncler","Mulberry","Prada","Saint Laurent","Sandqvist","Self Portrait","Skall Studio","Stella McCartney","The Row","Stand Studio","Valentino","Veja","Versace","Wood Wood","Vivienne Westwood","Diesel","Barbour","Helmut Lang","Calvin Klein","Axel Arigato","Rotate","Brunello Cucinelli","Loro Piana","Max Mara","Giorgio Armani","Emporio Armani","Fendi","Ferragamo"],
  B: ["Samsøe Samsøe","ADOORE","American Vintage","Asics","Blankens","Hunter","Lemaire","Munthe","New Balance","Nike","Nudie Jeans","Pernille Corydon","Resume","Saucony","REISS","Karen Millen","Rohe","Soeur","Madewell","Kings of Indigo"],
  C: ["M&S Autograph","Sosandar"],
} as const;

export type BrandTier = keyof typeof TIER_BRANDS;

export const VINTED_BRAND_IDS: Record<string, string> = {
  "Toteme": "308512",
  "Acne Studios": "14",
  "Filippa K": "621",
  "Tiger of Sweden": "1639",
  "Stine Goya": "89951",
  "Ganni": "14764",
  "By Malene Birger": "3890",
  "Rodebjer": "23526",
  "Hope Stockholm": "23527",
  "COS": "2921",
  "Our Legacy": "208254",
  "Balenciaga": "305",
  "Bottega Veneta": "1523",
  "Burberry": "218",
  "Chanel": "19",
  "Celine": "2307",
  "Chloe": "1142",
  "Dior": "34",
  "Gucci": "65",
  "Isabel Marant": "3362",
  "Jacquemus": "208274",
  "Levi's": "304",
  "Louis Vuitton": "28",
  "Maison Margiela": "3014",
  "Marni": "1021",
  "Miu Miu": "1038",
  "Moncler": "308",
  "Prada": "77",
  "Saint Laurent": "85",
  "Stella McCartney": "1267",
  "Valentino": "461",
  "Versace": "195",
  "Helmut Lang": "3358",
  "Calvin Klein": "99",
  "Max Mara": "984",
  "Fendi": "41",
  "Ralph Lauren": "88",
  "Barbour": "1757",
  "Dr Martens": "1423",
  "Veja": "208270",
  "Axel Arigato": "441835",
  "Sandqvist": "208283",
  "Patagonia": "1172",
  "Carhartt": "308",
  "Wood Wood": "208290",
  "Diesel": "35",
  "Gant": "566",
  "Mulberry": "308516",
  "House of Dagmar": "23504",
  "Dagmar": "23504",
  "Stand Studio": "208284",
  "Skall Studio": "441836",
  "Self Portrait": "208281",
  "ATP Atelier": "208258",
  "Jeanerica": "208272",
  "Baserange": "208261",
  "Sefr": "441834",
  "Flattered": "208268",
  "Eytys": "208267",
  "Little Liffner": "441832",
  "Soft Goat": "441837",
  "Rotate": "441833",
  "Baum und Pferdgarten": "208262",
};
